//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herbstregatta.Portal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Herbstregatta.Portal.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Person hinzufügen.
        /// </summary>
        internal static string AddPerson {
            get {
                return ResourceManager.GetString("AddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwaltungsbereich.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falls du dich für die Regatta anmelden willst, bist du hier falsch...
        /// </summary>
        internal static string AdministrationWrongAreaText {
            get {
                return ResourceManager.GetString("AdministrationWrongAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort der Verwaltung.
        /// </summary>
        internal static string AdminToken {
            get {
                return ResourceManager.GetString("AdminToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib das Passwort für die Verwaltung ein!.
        /// </summary>
        internal static string AdminTokenHelperText {
            get {
                return ResourceManager.GetString("AdminTokenHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwaltung der Ausschreibungen.
        /// </summary>
        internal static string AnnouncementManagement {
            get {
                return ResourceManager.GetString("AnnouncementManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selektierte Rennen zu einem Lauf zusammenfassen.
        /// </summary>
        internal static string AssignSelectedRacesToRun {
            get {
                return ResourceManager.GetString("AssignSelectedRacesToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sportler:in.
        /// </summary>
        internal static string Athlete {
            get {
                return ResourceManager.GetString("Athlete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Löschen kann nicht rückgängig gemacht werden!.
        /// </summary>
        internal static string AttentionDeleteMessage {
            get {
                return ResourceManager.GetString("AttentionDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahrgang.
        /// </summary>
        internal static string BirthYear {
            get {
                return ResourceManager.GetString("BirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot.
        /// </summary>
        internal static string Boat {
            get {
                return ResourceManager.GetString("Boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Boots.
        /// </summary>
        internal static string BoatName {
            get {
                return ResourceManager.GetString("BoatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verein.
        /// </summary>
        internal static string Club {
            get {
                return ResourceManager.GetString("Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der Ruderer.
        /// </summary>
        internal static string CountOfAthletes {
            get {
                return ResourceManager.GetString("CountOfAthletes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der gemeldeten Rennen.
        /// </summary>
        internal static string CountOfRaceEntries {
            get {
                return ResourceManager.GetString("CountOfRaceEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein neues Rennen erstellen.
        /// </summary>
        internal static string CreateNewRace {
            get {
                return ResourceManager.GetString("CreateNewRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person erstellen.
        /// </summary>
        internal static string CreatePerson {
            get {
                return ResourceManager.GetString("CreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Hinzufügen einer neuen Person zum Team wurde abgebrochen..
        /// </summary>
        internal static string CreatePersonAbortMessage {
            get {
                return ResourceManager.GetString("CreatePersonAbortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen eines Rennens.
        /// </summary>
        internal static string CreateRace {
            get {
                return ResourceManager.GetString("CreateRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Erstellen eines neues Rennen wurde abgebrochen..
        /// </summary>
        internal static string CreateRaceAbortMessage {
            get {
                return ResourceManager.GetString("CreateRaceAbortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein neues Rennen wurde erstellt..
        /// </summary>
        internal static string CreateRaceSuccessMessage {
            get {
                return ResourceManager.GetString("CreateRaceSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle ein neues Team..
        /// </summary>
        internal static string CreateTeam {
            get {
                return ResourceManager.GetString("CreateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Erstellen eines neuen Teams wurde abgebrochen..
        /// </summary>
        internal static string CreateTeamAbortMessage {
            get {
                return ResourceManager.GetString("CreateTeamAbortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein neues Team wurde erstellt..
        /// </summary>
        internal static string CreateTeamSuccessMessage {
            get {
                return ResourceManager.GetString("CreateTeamSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutz.
        /// </summary>
        internal static string DataProtection {
            get {
                return ResourceManager.GetString("DataProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutzerklärung.
        /// </summary>
        internal static string DataProtectionHeader {
            get {
                return ResourceManager.GetString("DataProtectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweis zur Datenspeicherung.
        /// </summary>
        internal static string DataProtectionHint {
            get {
                return ResourceManager.GetString("DataProtectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweis zur Datenspeicherung bitte beachte, dass deine eingegebenen Daten bis maximal 3 Monate nach Ende der Veranstaltung bei uns gespeichert werden. Meldungen werden mit den Informationen &quot;Name, Vorname Geburtsjahr und Teamzugehörigeit&quot; veröffentlicht. Falls du damit nicht einverstanden bist, melde dich doch einfach direkt bei uns. Wir finden sicherlich eine Lösung :).
        /// </summary>
        internal static string DataProtectionHintText {
            get {
                return ResourceManager.GetString("DataProtectionHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person entfernen.
        /// </summary>
        internal static string DeletePerson {
            get {
                return ResourceManager.GetString("DeletePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Entfernen der Person aus dem Team wurde abgebrochen..
        /// </summary>
        internal static string DeletePersonAbortMessage {
            get {
                return ResourceManager.GetString("DeletePersonAbortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Person wurde erfolgreich aus dem Team entfernt..
        /// </summary>
        internal static string DeletePersonSuccessMessage {
            get {
                return ResourceManager.GetString("DeletePersonSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rennen löschen?.
        /// </summary>
        internal static string DeleteRace {
            get {
                return ResourceManager.GetString("DeleteRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen der Meldung.
        /// </summary>
        internal static string DeleteRaceRegistration {
            get {
                return ResourceManager.GetString("DeleteRaceRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen der Meldung ist fehlgeschlagen!.
        /// </summary>
        internal static string DeleteRaceRegistrationFailedMessage {
            get {
                return ResourceManager.GetString("DeleteRaceRegistrationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Löschen der Meldung war erfolgreich!.
        /// </summary>
        internal static string DeleteRaceRegistrationSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteRaceRegistrationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldungen als Exceldatei herunterladen.
        /// </summary>
        internal static string DownloadEntriesAsExcel {
            get {
                return ResourceManager.GetString("DownloadEntriesAsExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten des Rennens.
        /// </summary>
        internal static string EditRace {
            get {
                return ResourceManager.GetString("EditRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Bearbeiten des Rennens ist fehlgeschlagen..
        /// </summary>
        internal static string EditRaceFailedMessage {
            get {
                return ResourceManager.GetString("EditRaceFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten der Meldung.
        /// </summary>
        internal static string EditRaceRegistration {
            get {
                return ResourceManager.GetString("EditRaceRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Rennen wurde bearbeitet..
        /// </summary>
        internal static string EditRaceSuccessMessage {
            get {
                return ResourceManager.GetString("EditRaceSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahl aktivieren.
        /// </summary>
        internal static string EnableSelection {
            get {
                return ResourceManager.GetString("EnableSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nummer der Meldung.
        /// </summary>
        internal static string EntryId {
            get {
                return ResourceManager.GetString("EntryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Informationen zu den Rennen.
        /// </summary>
        internal static string FurtherInformation {
            get {
                return ResourceManager.GetString("FurtherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ist das Boot gesteuert?.
        /// </summary>
        internal static string HasCoxQuestion {
            get {
                return ResourceManager.GetString("HasCoxQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        internal static string Imprint {
            get {
                return ResourceManager.GetString("Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sportler:innen.
        /// </summary>
        internal static string ListOfAthletes {
            get {
                return ResourceManager.GetString("ListOfAthletes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeldete Rennen.
        /// </summary>
        internal static string ListOfRaceRegistrations {
            get {
                return ResourceManager.GetString("ListOfRaceRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelleninhalt laden.
        /// </summary>
        internal static string LoadTable {
            get {
                return ResourceManager.GetString("LoadTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Login Versuch wurde abgebrochen..
        /// </summary>
        internal static string LoginAbortMessage {
            get {
                return ResourceManager.GetString("LoginAbortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Login ist fehlgeschlagen..
        /// </summary>
        internal static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melde dich an um dich für ein Rennen zu registrieren.
        /// </summary>
        internal static string LoginHelperText {
            get {
                return ResourceManager.GetString("LoginHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Login war erfolgreich..
        /// </summary>
        internal static string LoginSuccessMessage {
            get {
                return ResourceManager.GetString("LoginSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Kategorie wird benötigt!.
        /// </summary>
        internal static string MissingCategory {
            get {
                return ResourceManager.GetString("MissingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Beschreibung wird benötigt!.
        /// </summary>
        internal static string MissingDescription {
            get {
                return ResourceManager.GetString("MissingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort für diese Aktion fehlt!.
        /// </summary>
        internal static string MissingPassword {
            get {
                return ResourceManager.GetString("MissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Name für das Rennen wird benötigt!.
        /// </summary>
        internal static string MissingRaceName {
            get {
                return ResourceManager.GetString("MissingRaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Token wird für diese Aktion benötigt!.
        /// </summary>
        internal static string MissingToken {
            get {
                return ResourceManager.GetString("MissingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dem Team sind noch keine Personen hinzugefügt worden..
        /// </summary>
        internal static string NoPersonsInTeam {
            get {
                return ResourceManager.GetString("NoPersonsInTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es sind noch keine Teams erstellt worden, bitte erstelle dein Team zum Fortfahren..
        /// </summary>
        internal static string NoTeamsConfigured {
            get {
                return ResourceManager.GetString("NoTeamsConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist noch kein Team ausgewählt. Bitte wähle dein Team aus, um dich anzumelden..
        /// </summary>
        internal static string NoTeamSelectedMessage {
            get {
                return ResourceManager.GetString("NoTeamSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles klar!.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Person wurde dem Team hinzugefügt..
        /// </summary>
        internal static string PersonAddedToTeam {
            get {
                return ResourceManager.GetString("PersonAddedToTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person wurde nicht gefunden. Id={0}.
        /// </summary>
        internal static string PersonNotFound {
            get {
                return ResourceManager.GetString("PersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rennen.
        /// </summary>
        internal static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausschreibung.
        /// </summary>
        internal static string RaceInvitation {
            get {
                return ResourceManager.GetString("RaceInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rennen.
        /// </summary>
        internal static string RaceName {
            get {
                return ResourceManager.GetString("RaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr.
        /// </summary>
        internal static string RaceNumber {
            get {
                return ResourceManager.GetString("RaceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung zum Rennen.
        /// </summary>
        internal static string RaceRegistration {
            get {
                return ResourceManager.GetString("RaceRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einteilung der Rennen.
        /// </summary>
        internal static string RaceScheduling {
            get {
                return ResourceManager.GetString("RaceScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahn.
        /// </summary>
        internal static string RaceTrack {
            get {
                return ResourceManager.GetString("RaceTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platzierung.
        /// </summary>
        internal static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeldete Rennen.
        /// </summary>
        internal static string RegisteredRaces {
            get {
                return ResourceManager.GetString("RegisteredRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier siehst du deine gemeldeten Rennen.
        /// </summary>
        internal static string RegisteredRacesHelperText {
            get {
                return ResourceManager.GetString("RegisteredRacesHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung für ein Rennen.
        /// </summary>
        internal static string RegisterForRace {
            get {
                return ResourceManager.GetString("RegisterForRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rennmeldung.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für das Rennen anmelden.
        /// </summary>
        internal static string RegistrationAfterLoginText {
            get {
                return ResourceManager.GetString("RegistrationAfterLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier kannst du dich nach dem Login für das Rennen anmelden..
        /// </summary>
        internal static string RegistrationBeforeLoginText {
            get {
                return ResourceManager.GetString("RegistrationBeforeLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier kannst du deine Meldungen vornehmen.
        /// </summary>
        internal static string RegistrationHelperText {
            get {
                return ResourceManager.GetString("RegistrationHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Anmeldeschluss ist vorbei. Falls du Änderungswünsche hast, melde dich bitte beim Orga Team..
        /// </summary>
        internal static string RegistrationLocked {
            get {
                return ResourceManager.GetString("RegistrationLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldeportal.
        /// </summary>
        internal static string RegistrationPortal {
            get {
                return ResourceManager.GetString("RegistrationPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederholte Eingabe des Passworts.
        /// </summary>
        internal static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lauf Nr..
        /// </summary>
        internal static string RunNumber {
            get {
                return ResourceManager.GetString("RunNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist angemeldet mit dem Team &quot;{0}&quot;.
        /// </summary>
        internal static string SelectedTeam {
            get {
                return ResourceManager.GetString("SelectedTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle ein Teammitglied aus.
        /// </summary>
        internal static string SelectTeamMember {
            get {
                return ResourceManager.GetString("SelectTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktionen zum Bearbeiten.
        /// </summary>
        internal static string ShowEditOption {
            get {
                return ResourceManager.GetString("ShowEditOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortiere nach.
        /// </summary>
        internal static string SortByLabel {
            get {
                return ResourceManager.GetString("SortByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startzeit.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitnahme.
        /// </summary>
        internal static string Stopwatch {
            get {
                return ResourceManager.GetString("Stopwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tauschen.
        /// </summary>
        internal static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Mitglieder.
        /// </summary>
        internal static string TeamMembers {
            get {
                return ResourceManager.GetString("TeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier kannst du Mitglieder zu deinem Team hinzufügen.
        /// </summary>
        internal static string TeamMembersHelperText {
            get {
                return ResourceManager.GetString("TeamMembersHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Team Passwort oder das Passwort der Verwaltung.
        /// </summary>
        internal static string TeamOrAdminTokenHelperText {
            get {
                return ResourceManager.GetString("TeamOrAdminTokenHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort des Teams.
        /// </summary>
        internal static string TeamPassword {
            get {
                return ResourceManager.GetString("TeamPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen dein Verein aus und melde dich mit deinem Passwort an..
        /// </summary>
        internal static string TeamSelectionHelperText {
            get {
                return ResourceManager.GetString("TeamSelectionHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort für die Teamerstellung.
        /// </summary>
        internal static string TeamToken {
            get {
                return ResourceManager.GetString("TeamToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebe das Passwort ein, dass du von uns bekommen hast!.
        /// </summary>
        internal static string TeamTokenHelperText {
            get {
                return ResourceManager.GetString("TeamTokenHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitplan.
        /// </summary>
        internal static string Timetable {
            get {
                return ResourceManager.GetString("Timetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tübinger Herbstregatta.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer:in.
        /// </summary>
        internal static string Trainer {
            get {
                return ResourceManager.GetString("Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Aktualisieren der Meldung ist fehlgeschlagen..
        /// </summary>
        internal static string UpdateRaceRegistrationFailedMessage {
            get {
                return ResourceManager.GetString("UpdateRaceRegistrationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Aktualisieren der Meldung war erfolgreich..
        /// </summary>
        internal static string UpdateRaceRegistrationSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateRaceRegistrationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
